BodyMaster/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.accounts.urls',namespace="accounts")),
]

apps/accounts/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login,logout
from .forms import MyLoginForm
urlpatterns = [
    url(r'^$',login,{'template_name':'accounts/login.html','form_class':MyLoginForm,'redirect_authenticated_user':True},name='login'),
    url(r'^logout$',logout,{'next_page':'/'},name='logout'),

    url(r'^home$',login_required(HomeView.as_view()), name='home'),
    url(r'^product/delete/(?P<pk>\d+)$', login_required(product_delete), name='product_delete'),
    url(r'^compra/delete/(?P<pk>\d+)$', login_required(compra_delete.as_view()), name='compra_delete'),

    url(r'^result_type/$',login_required(result), name='result'),
    url(r'^cart/$',login_required(CartView.as_view()), name='cart'),
    url(r'^comprar/$',login_required(add_purchase), name='comprar'),
    url(r'^compras$',login_required(ComprasView.as_view()), name='compras'),
    url(r'^add/product$',login_required(add_product), name='addProduct'),
    url(r'^detail/product/(?P<pk>\d+)$',login_required(ProductDetailView.as_view()), name='detail'),
    url(r'^deleteSession/$',login_required(deleteSession), name='deleteSession'),
    url(r'^finalizar/$',login_required(finalizar), name='finalizar'),
]

templates/partials/cart_count.html
<a href="{% url  'accounts:cart' %}" class="cart">
  <i class="icon-cart menu__icon"></i>
  <p class="cart__count">{% if add %}{{add}} {% else %}{{request.session.product|getItemsCount}}{% endif %}</p>
</a>

templates/partials/create_article.html
<form id="formCreate" class="form" action="{% url  'accounts:addProduct' %}" method="POST">
  <div class="modal-dialog animated">
    <div class="modal-content">
        <div class="modal-header">
          <strong class="modal__title">Añadir un articulo</strong>
        </div>
        <div class="modal-body">
            {% csrf_token %}
            {% for field in form %}
            <div class="form__cont">
             <label class="form__label">{{ field.label }}</label>
             {{ field }}
            </div>
            {% endfor %}
        </div>

        <div class="modal-footer">
          <button id='create' class="btn btn--save" type="submit">GUARDAR</button>
          <button class="btn close" type="button">Close</button>
        </div>
    </div>
  </div>
</form>

templates/partials/delete_form.html
<form id="formDelete" class="form" action="{% url  'accounts:product_delete' object.id %}" method="POST">{% csrf_token %}
  <div class="modal-dialog animated">
    <div class="modal-content">
        <div class="modal-header modal-header--delete">
          <strong class="modal__title">Eliminar un articulo</strong>
        </div>
        <div class="modal-body--delete">
          <p class="modal__text">¿Seguro que desa eliminar {{object.nombre}}?</p>
        </div>

        <div class="modal-footer">
          <button  class="btn btn--save" type="submit">ELIMINAR</button>
          <button class="btn close" type="button">Close</button>
        </div>
    </div>
  </div>
</form>

templates/partials/header.html
<header class="header">
  {% load static %}
  {% if  user.is_authenticated %}
        <div class="menu_container">
          <div class="header__con">
            <div class="header__logo">
              <img src="{% static 'img/bm.png' %}" class="logo">
              <h1 class="header__title">BODY MASTER</h1>
            </div>



            <label for="check" class="check_menu"> <i class="icon-menu"></i></label>
            <input type="checkbox" id="check" class="check">

            <nav class="menu">
              <ul class="menu__ul">
                <li class="menu__li menu__li--X"><i class="icon-cross"></i></li>
                <li class="menu__li">
                  <a href="{% url  'accounts:home' %}" class="menu__a">
                    <i class="icon-home menu__icon"></i>
                    <p class="menu__p">INICIO</p>
                  </a>
                </li>

                <li class="menu__li">
                  <a href="{% url  'accounts:compras' %}" class="menu__a">
                    <i class="icon-truck menu__icon"></i>
                    <p class="menu__p">COMPRAS</p>
                  </a>
                </li>

                <li class="menu__li menu__salir">
                  <a href="{% url  'accounts:logout' %}" class="menu__a">
                    <i class="icon-switch menu__icon"></i>
                    <p class="menu__p">SALIR</p>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
          <div id="cart">
            {% include 'partials/cart_count.html' %}
          </div>


        </div>
  {% else %}
    <div class="menu_container">
      <div class="header__con">
        <div class="header__logo">
          <img src="{% static 'img/bm.png' %}" class="logo">
          <h1 class="header__title">BODY MASTER</h1>
        </div>
      </div>

    </div>
  {% endif %}

</header>

templates/partials/html_result.html
{% for x in object_list  %}
  <div class="item">
     <!-- <div class="item__img">
        <img src="media/{{x.img}}" class="img">
    </div> -->
    {% if user.is_superuser %}
      <div class="item__delete">
          <button data-url={% url 'accounts:product_delete' x.pk %} type="submit" class="del" id="product_delete">
            <i class="icon-cancel-circle"></i>
          </button>
      </div>
    {% endif %}

    <div class="item__info">
      <h3 class="item__name">{{x.nombre}}</h3>
      <span class="item__cant">Unidades: {{x.cantidad}}</span>
      <h4 class="item__price">${{x.precio}}</h4>
    </div>
    <div class="item__btns">
      {#{{request.session.count|get_cart:x.pk}}  #}
      <button value="{{request.session.count|get_cart:x.pk}}/{{x.cantidad}}" data-url="{{x.id}}" type="button" class="btn btn--compra" id="comprar">Añadir</button>
      {% if user.is_superuser %}
          <a href="{% url  'accounts:detail' x.pk %}" class="btn">Detalles</a>
      {% endif %}

    </div>
  </div>

  <!-- {% empty %}
  <div class="text">
      <h1 class="text__noFound">No hay {{name}}</h1>
  </div>  -->
{% endfor %}