BodyMaster/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.accounts.urls',namespace="accounts")),
]

apps/accounts/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login,logout
from .forms import MyLoginForm
urlpatterns = [
    url(r'^$',login,{'template_name':'accounts/login.html','form_class':MyLoginForm,'redirect_authenticated_user':True},name='login'),
    url(r'^logout$',logout,{'next_page':'/'},name='logout'),

    url(r'^home$',login_required(HomeView.as_view()), name='home'),
    url(r'^product/delete/(?P<pk>\d+)$', login_required(product_delete), name='product_delete'),
    url(r'^compra/delete/(?P<pk>\d+)$', login_required(compra_delete.as_view()), name='compra_delete'),

    url(r'^result_type/$',login_required(result), name='result'),
    url(r'^cart/$',login_required(CartView.as_view()), name='cart'),
    url(r'^comprar/$',login_required(add_purchase), name='comprar'),
    url(r'^compras$',login_required(ComprasView.as_view()), name='compras'),
    url(r'^add/product$',login_required(add_product), name='addProduct'),
    url(r'^detail/product/(?P<pk>\d+)$',login_required(ProductDetailView.as_view()), name='detail'),
    url(r'^deleteSession/$',login_required(deleteSession), name='deleteSession'),
    url(r'^finalizar/$',login_required(finalizar), name='finalizar'),
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.
class Articulo(models.Model):
    TYPES=(
        (1,'PROTEINAS'),(2,'OXIDOS'),
        (3,'QUEMADORES'),(4,'GANADORES'),
        (5,'CREATINAS'),(6,'GLUTAMINAS'),
        (7,'CARNITINAS'),(8,'CLS'),
        (9,'PRECURSORES'),(10,'MULTIVITAMINICOS'),
        (11,'ACCESORIOS'),(12,'BCCAS'),(13,'AMINOACIDOS'),
    )

    nombre = models.CharField(max_length=100)
    precio = models.FloatField(default=0)
    cantidad = models.PositiveSmallIntegerField(default=0)
    tipo = models.PositiveSmallIntegerField(blank=False, null=False, choices=TYPES)
    # img = models.ImageField(upload_to="imagenes/", null=True,blank=True,default='/imagenes/default.png')
    dec = models.TextField(blank=True,null=True)
    # ##################
    codigo_de_barras = models.CharField(blank=True,null=True, max_length=120)

    def __str__(self):
        return self.nombre


class Compra(models.Model):
    productos = models.ManyToManyField(Articulo)
    usuario=models.ForeignKey(User,null=True,blank=True)
    total = models.PositiveIntegerField(blank=True, null=True)
    fecha = models.DateField(auto_now_add=True,auto_now=False)
    def __str__(self):
        return 'TOTAL: {}'.format(self.total)

apps/accounts/forms.py
from django import forms
from .models import *
from django.utils.translation import ugettext_lazy as _
from  django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

class MyLoginForm(AuthenticationForm):
    def __init__(self,*args,**kwargs):
        super(MyLoginForm,self).__init__(*args,**kwargs)
        self.fields['username'].label='Nombre de usuario'
        self.fields['password'].label='Contraseña'
        self.fields['username'].widget.attrs['class']='login_field'
        self.fields['password'].widget.attrs['class']='login_field'
        self.fields['username'].widget.attrs['placeholder']='Nombre de usuario'
        self.fields['password'].widget.attrs['placeholder']='Contraseña'
    class Meta:
        model=User
class ProductForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super(ProductForm,self).__init__(*args,**kwargs)
        for i in self.fields:
            self.fields[i].widget.attrs['class']='form__field'

    class Meta:
        model=Articulo
        exclude=['codigo_de_barras','dec']


class ProductUpdateForm(forms.ModelForm):
    # img=forms.ImageField(label=_('Imagen'),required=False,widget=forms.FileInput)
    def __init__(self,*args,**kwargs):
        super(ProductUpdateForm,self).__init__(*args,**kwargs)
        for i in self.fields:
            self.fields[i].widget.attrs['class']='form__field'
        # self.fields['img'].widget.attrs['class']='form__field form__field--img'
        # self.fields['img'].widget.attrs['id']='upload'

    class Meta:
        model=Articulo
        exclude=['codigo_de_barras','dec']

apps/accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import TemplateView,DetailView,UpdateView,ListView,DeleteView
from django.http import JsonResponse
from django.template.loader import render_to_string
from .models import *
from .forms import *
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse, reverse_lazy
from django.core.mail import EmailMessage,EmailMultiAlternatives
from django.template.defaulttags import register
from collections import defaultdict
from django.http import HttpResponseRedirect
from django.utils.html import strip_tags

@register.filter
def get_cart(dic,key,*args,**kwargs):
    print("DICT: "+str(dic))
    for i in dic:
        if str(key) in i:
            return i.get(str(key))
@register.filter
def getItemsCount(i):
    return len(i)



# Create your views here.

class compra_delete(DeleteView):
    success_url=reverse_lazy('accounts:compras')
    model=Compra

class HomeView(TemplateView):
    template_name='accounts/index.html'
    def get_context_data(self,*args,**kwargs):
        context=super(HomeView,self).get_context_data(*args,**kwargs)
        context['object_list']=Articulo.objects.all()
        if "count" not in self.request.session:
            self.request.session['count']=[]
            for i in context['object_list']:
                aux=self.request.session['count']
                a=dict([(str(i.pk),i.cantidad)])
                aux.append(a)
                self.request.session['count']=aux
        else:
            temp=self.request.session['count']
            all_ob=context['object_list']
            for i in all_ob:
                tempDict=dict([(str(i.pk),i.cantidad)])
                if tempDict not in temp:
                    temp.append(tempDict)
            self.request.session['count']=temp

        self.request.session.modified = True
        self.request.session['search_product']=0
        return context

class ComprasView(ListView):
    template_name='accounts/compras.html'

    def get_queryset(self):
        return Compra.objects.all().order_by('-fecha')

class CartView(TemplateView):
    template_name='accounts/cart.html'
    def get_context_data(self,*args,**kwargs):
        from collections import Counter
        context=super(CartView,self).get_context_data(*args,**kwargs)

        if 'product' in self.request.session:
            products=self.request.session['product']
            repeat=Counter(products)
            list_pk= [i for i in repeat if repeat[i]>1]
            list_pk= list_pk+[i for i in repeat if repeat[i]==1]
            context['object_list']=[]
            total=0
            for pk in list_pk:
                product=Articulo.objects.get(pk=pk)
                total=total+(product.precio*repeat[pk])
                context['object_list'].append({'nombre':product.nombre,'precio':product.precio,'cantidad':repeat[pk]})
            context['total']=total
        return context

def result(request):
    data=dict()
    typeProduct=request.GET['type']
    request.session['search_product']=typeProduct
    nameProduct=request.GET['name']
    if int(typeProduct) > 0:
        articles=Articulo.objects.filter(tipo=typeProduct).order_by('nombre')
    else:
        articles=Articulo.objects.all().order_by('nombre')
    context={
        'object_list':articles,
        'name':nameProduct,
        't':len(articles),
    }
    data['html_result']=render_to_string('partials/html_result.html',context,request=request)
    return JsonResponse(data)

def sessionValues(request,idCompra):
    if 'product' in request.session:
        s=request.session['product']
        s.append(idCompra)
        request.session['product']=s
    else:
        request.session['product']=[idCompra]

def add_purchase(request):
    data=dict()
    idCompra=int(request.GET['idCompra'])
    temp=request.session['count']
    for i in temp:
        newId=str(idCompra)
        if newId in i:
            i[newId]=i.get(newId)-1
    print("REDUCE: "+str(temp))
    add=int(request.GET['add'])
    sessionValues(request,idCompra)
    context={'add':add}
    # print(context)
    data['cart']=render_to_string('partials/cart_count.html',context)

    return JsonResponse(data)

# @csrf_protect
def save_form(request,form,template_name):
    data=dict()
    if request.method =='POST':
        if form.is_valid():
            form.save()
            data['form_is_valid']=True
            products=Articulo.objects.filter(tipo=request.session['search_product'])
            data['product']=request.session['search_product']
            data['html_list']=render_to_string('partials/html_result.html',{'object_list':products},request=request)
        else:
            data['form_is_valid']=False
    context={'form':form}
    data['html']=render_to_string(template_name,context,request=request)
    return JsonResponse(data)

@csrf_protect
def add_product(request):
    if request.method=='POST':
        form=ProductForm(request.POST)
    else:
        form=ProductForm()
    return save_form(request,form,'partials/create_article.html')


class ProductDetailView(UpdateView):
    model = Articulo
    success_url = reverse_lazy('accounts:home')
    template_name = 'accounts/detail_product.html'
    form_class=ProductUpdateForm
    def form_valid(self,form):
        super(ProductDetailView,self).form_valid(form)
        pk=form.instance.pk
        newCant=form.instance.cantidad
        temp=self.request.session['count']

        for i in temp:
            if str(pk) in i:
                i[str(pk)]=newCant
        self.request.session['count']=temp
        print("NEW CANTIDAD: "+str(self.request.session['count']))
        return HttpResponseRedirect(self.get_success_url())
def deleteSession(request):
    del request.session['product']
    del request.session['count']
    return JsonResponse({'done':'done'})

def finalizar(request):
    from collections import Counter
    data=dict()
    compra=Compra()
    compra.save()
    total=0
    repeat=dict(Counter(request.session['product']))
    for i in request.session['product']:
        p=Articulo.objects.get(pk=i)
        total=total+(p.precio)
        compra.productos.add(p)

    names=[]
    email_context=[]
    for pk,cant in repeat.items():
        p=Articulo.objects.get(pk=pk)
        email_context.append({'nombre':p.nombre,'precio':p.precio,'cantidad':cant})
        names.append(str(cant)+"x"+str(p.nombre))
        p.cantidad=p.cantidad-cant
        p.save()
    compra.total=total
    compra.usuario=request.user
    first_name,last_name=request.user.first_name,request.user.last_name
    fullname='{0} {1}'.format(first_name,last_name).upper()
    compra.save()
    print(first_name,last_name)
    del request.session['product']
    subject,from_email,to='BodyMaster {}'.format(compra.fecha),'teambodymaster@gmail.com','armando_bonilla4@hotmail.com'
    print('COMPRA REALIZADA POR: '+fullname)
    html_content=render_to_string('accounts/email_cart.html',{'object_list':email_context,'total':total,'nombre':fullname})
    text_content=strip_tags(html_content)
    msg=EmailMultiAlternatives(subject,text_content,from_email,[to,'photoscastillo2017@gmail.com'])
    msg.attach_alternative(html_content,'text/html')
    msg.send()

    return JsonResponse(data)

def product_delete(request,pk):
    product=get_object_or_404(Articulo,pk=pk)
    data=dict()
    if request.method=='POST':
        product.delete()
        data['form_is_valid']=True
        products=Articulo.objects.filter(tipo=request.session['search_product'])
        context={'object_list':Articulo.objects.all()}
        data['html_list']=render_to_string('partials/html_result.html',context,request=request)
        if 'product' in request.session:
            del request.session['product']
        del request.session['count']
    else:
        context={'object':product}
        data['html']=render_to_string('partials/delete_form.html',context,request=request)
    return JsonResponse(data)

templates/accounts/cart.html
{% extends '../base.html' %}
{% block title %}Cart{% endblock title %}

{% block content %}
  {% include 'partials/header.html' %}
  <main class="main">
    <div class="cart__cont">
      <div class="cart__item">
        <h4>CART</h4>
      </div>
      {% if request.session.product %}
        {% for x in object_list  %}
        <div class="cart__item">
          <p class="cart__p"><span class="cart__span">{{x.cantidad}}x</span>{{x.nombre}}</p>
          <span class="cart__span">${{x.precio}}</span>
        </div>
        {% endfor %}
        <div class="cart__item cart__item--total">
          <p class="cart__total">TOTAL:</p>
          <p class="cart__total--text">${{total}}</p>
        </div>
        <div class="cart__btn">
          <button id="finalizar" data-url="{% url  'accounts:finalizar' %}" type="button" class="btn btn__cart" value="{{product_list_remove}}">FINALIZAR</button>
          <button class="btn btn__cart btn__cart--del " type="button" id="deleteSession">Reiniciar compra</button>
        </div>
    </div>
      {% else %}
          <div class="cart__item cart__item--no">
            <p>NO HAY ARTICULOS AÑADIDOS.</p>
          </div>

      {% endif %}

  </main>
  <div id="loading">

  </div>

{% endblock content %}

templates/accounts/compras.html
{% extends '../base.html' %}
{% block title %}Compras{% endblock title %}

{% block content %}
  {% include 'partials/header.html' %}
  <main class="main">
    <div class="table_con">
      <table class="table">
        <thead class="table__head">
          <tr>
            <th>REALIZADA POR</th>
            <th>FECHA</th>
            <th>TOTAL</th>
            <th>--</th>
          </tr>
        </thead>
        <tbody class="table__body">
          {% for x in object_list  %}
                <tr>
                  <td>{{x.usuario.first_name}}</td>
                  <td>{{x.fecha}}</td>
                  <td>${{x.total}}</td>
                  <td>
                    <form  action="{% url  'accounts:compra_delete' x.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" id="delete_compra">
                            <i class="icon-cross"></i>
                        </button>
                    </form>
                  </td>
                </tr>
          {% empty %}
            <tr>
              <th colspan="4">NO HAY COMPRAS</th>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

  </main>

  <div id="loading">
  </div>

{% endblock content %}

templates/accounts/detail_product.html
{% extends '../base.html' %}
{% block title %}Detail Product{% endblock title %}
{% block content %}
  {% include 'partials/header.html' %}

  <div class="container">

    <form  class="form margin-top" method="post">{% csrf_token %}
      <div class="modal-dialog animated">
        <div class="modal-content">
            <div class="modal-header">
              <strong class="modal__title">Detalle {{object}}</strong>
            </div>
            <div class="modal-body">
                {% csrf_token %}
                {% for field in form %}
                <div class="form__cont">
                 <label class="form__label">{{ field.label }}</label>
                 {{ field }}
                </div>
                {% endfor %}
            </div>

            <div class="modal-footer">
              <button class="btn btn--save" type="submit">GUARDAR</button>
            </div>
        </div>
      </div>
    </form>
    <!-- {# <h1 class="title">Información de {{object}}</h1>
    <form class="form__detail" method="post" enctype='multipart/form-data'>{% csrf_token %}
      {% for field in form %}
        {% if field.label != 'Imagen' %}
          <div class="form__cont">
           <label class="form__label">{{ field.label }}</label>
           {{ field }}
          </div>
        {% else %}
        <div class="form__cont--img">
         <label class="form__label upload" for="upload">Subir Imagen</label>
         {{ field }}
        </div>
        {% endif %}

      {% endfor %}
      <button type="submit" name="button" class="btn btn--add-up">Guardar</button>
    </form> #} -->
  </div>
{% endblock content %}

templates/accounts/email_cart.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  </head>
  <body>
    <main class="  width: 95%; height: calc(100vh - 3.5rem); background: lighten(#F9F9F9,2); margin: auto; height: 100%;">
      <div style="max-width: 400px;">
        <div style="padding:10; border-bottom: 1px solid rgba(0,0,0,0.2);">
          <h4>COMPRA REALIZADA POR {{nombre}}</h4>
        </div>
          {% for x in object_list  %}
          <div style="padding:10; border-bottom: 1px solid rgba(0,0,0,0.2);">
            <p><span style=" color: #FF1D19; margin-right: 2px;">{{x.cantidad}}x</span>{{x.nombre}}</p>
            <span style="color: #FF1D19; margin-right: 2px;">${{x.precio}}</span>
          </div>
          {% endfor %}
          <div style="padding:10; border-bottom: 1px solid rgba(0,0,0,0.2); display: flex; justify-content: space-between;">
            <p style="font-weight: bold; font-size: 24px;">TOTAL:</p>
            <p style="font-weight: bold; font-size: 24px;">${{total}}</p>
          </div>
      </div>
    </main>
  </body>
</html>

templates/accounts/index.html
{% extends '../base.html' %}
{% block title %}Home({{user.first_name}}){% endblock title %}
{% block content %}
  {% include 'partials/header.html' %}
  <main class="main">
  <div class="search_pane">
      <select class="select" name="">
        <option value="0">---</option>
        <option value="1">Proteínas</option>
        <option value="2">Óxidos</option>
        <option value="3">Quemadores</option>
        <option value="4">Ganadores</option>
        <option value="5">Creatinas</option>
        <option value="6">Glutaminas</option>
        <option value="7">Carnitinas</option>
        <option value="8">CLA</option>
        <option value="9">Precursores</option>
        <option value="10">Multivitaminico</option>
        <option value="11">Accesorios</option>
        <option value="12">BCCA's</option>
        <option value="13">Aminoácidos</option>

      </select>

      <button data-url="{% url  'accounts:addProduct' %}" type="button"  class="btn btn--add" id="addProduct"><i class="icon-plus"></i><span class="btn__text">Agregar</span></button>


    </div>

    <section class="gallery__content">
        <div class="gallery__title">
            <h1 id="item__total" class="item__total"></h1>
        </div>
        <div id="result" class="gallery">
          {% include 'partials/html_result.html' %}
        </div>
    </section>
  </main>
  <div id="modal" class="modal"></div>
  <div id="loading"></div>
  <div id="Addloading">
  </div>
{% endblock content %}

templates/accounts/login.html
{% extends '../base.html' %}
{% block title %}Body Master{% endblock title %}
{% block content %}
  {% include 'partials/header.html' %}
  <div class="login_con">

    <form class="login_form" method="post">
      <div class="login-text_cont">
        <h1>Login</h1>
      </div>
      {% csrf_token %}
      {% for field in form %}
      <div class="form__cont">
       {# <label class="form__label">{{ field.label }}</label> #}
       {{ field }}
      </div>
      {% endfor %}
      <div class="form__cont">
       <button class="btn-login" type="submit" name="button">Ingresar</button>
      </div>
    </form>
  </div>
{% endblock content %}